# Generated by Django 5.1.1 on 2024-12-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_postmodel_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('grade', models.SmallIntegerField(max_length=12)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
            ],
        ),
    ]
