# Generated by Django 5.1.1 on 2024-12-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_profilemodel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='grade',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
