# Generated by Django 5.1.1 on 2024-12-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_postmodel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pfp',
            field=models.ImageField(blank=True, default='profile-placeholder.png', null=True, upload_to='profile_picture/'),
        ),
    ]
