# Generated by Django 5.1.1 on 2024-12-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_profilemodel_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
